# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cserver.proto\"\x1c\n\x0cReadyService\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\x0bReadyStatus\x12\r\n\x05ready\x18\x01 \x01(\x08\")\n\nReadyEntry\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05ready\x18\x02 \x01(\x08\"\'\n\tReadyList\x12\x1a\n\x05\x65ntry\x18\x01 \x03(\x0b\x32\x0b.ReadyEntry2\x8d\x01\n\x05Ready\x12\x30\n\x0fRegisterService\x12\r.ReadyService\x1a\x0c.ReadyStatus\"\x00\x12&\n\x05Ready\x12\r.ReadyService\x1a\x0c.ReadyStatus\"\x00\x12*\n\x0cGetInventory\x12\x0c.ReadyStatus\x1a\n.ReadyList\"\x00\x62\x06proto3'
)




_READYSERVICE = _descriptor.Descriptor(
  name='ReadyService',
  full_name='ReadyService',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ReadyService.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=44,
)


_READYSTATUS = _descriptor.Descriptor(
  name='ReadyStatus',
  full_name='ReadyStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ready', full_name='ReadyStatus.ready', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=74,
)


_READYENTRY = _descriptor.Descriptor(
  name='ReadyEntry',
  full_name='ReadyEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ReadyEntry.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ready', full_name='ReadyEntry.ready', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=117,
)


_READYLIST = _descriptor.Descriptor(
  name='ReadyList',
  full_name='ReadyList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entry', full_name='ReadyList.entry', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=158,
)

_READYLIST.fields_by_name['entry'].message_type = _READYENTRY
DESCRIPTOR.message_types_by_name['ReadyService'] = _READYSERVICE
DESCRIPTOR.message_types_by_name['ReadyStatus'] = _READYSTATUS
DESCRIPTOR.message_types_by_name['ReadyEntry'] = _READYENTRY
DESCRIPTOR.message_types_by_name['ReadyList'] = _READYLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReadyService = _reflection.GeneratedProtocolMessageType('ReadyService', (_message.Message,), {
  'DESCRIPTOR' : _READYSERVICE,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:ReadyService)
  })
_sym_db.RegisterMessage(ReadyService)

ReadyStatus = _reflection.GeneratedProtocolMessageType('ReadyStatus', (_message.Message,), {
  'DESCRIPTOR' : _READYSTATUS,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:ReadyStatus)
  })
_sym_db.RegisterMessage(ReadyStatus)

ReadyEntry = _reflection.GeneratedProtocolMessageType('ReadyEntry', (_message.Message,), {
  'DESCRIPTOR' : _READYENTRY,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:ReadyEntry)
  })
_sym_db.RegisterMessage(ReadyEntry)

ReadyList = _reflection.GeneratedProtocolMessageType('ReadyList', (_message.Message,), {
  'DESCRIPTOR' : _READYLIST,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:ReadyList)
  })
_sym_db.RegisterMessage(ReadyList)



_READY = _descriptor.ServiceDescriptor(
  name='Ready',
  full_name='Ready',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=161,
  serialized_end=302,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegisterService',
    full_name='Ready.RegisterService',
    index=0,
    containing_service=None,
    input_type=_READYSERVICE,
    output_type=_READYSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Ready',
    full_name='Ready.Ready',
    index=1,
    containing_service=None,
    input_type=_READYSERVICE,
    output_type=_READYSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetInventory',
    full_name='Ready.GetInventory',
    index=2,
    containing_service=None,
    input_type=_READYSTATUS,
    output_type=_READYLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_READY)

DESCRIPTOR.services_by_name['Ready'] = _READY

# @@protoc_insertion_point(module_scope)
